event_db:
  host: 192.168.65.52
  #host: 159.93.221.14
  port: 5000
  db_name: event_db
  user: postgres
  password: example

condition_db:
  host: 192.168.65.52
  #host: 159.93.221.14
  port: 5001
  db_name: bmn_db
  user: user
  password: user_pass

database_auth: True

#ldap_auth:
#  ldap_server: 127.0.0.1
#  ldap_port: 3890
#  user_dn_format: "uid=%s,cn=users,cn=accounts,dc=jinr,dc=ru"
#  ldap_username: shift
#  ldap_password: shift
#  writer_group_dn: "cn=bmneventwriter,cn=groups,cn=accounts,dc=jinr,dc=ru"
#  admin_group_dn: "cn=bmneventadmin,cn=groups,cn=accounts,dc=jinr,dc=ru"

title: BM@N Event Metadata System

# Note: we now support only one page per EMS instance
pages:
  - name: BM@N Events
    api_url: /event_api/v1
    db_table_name: event
    default_limit_web: 100
    parameters:
      - name: track_number
        type: int
        intervals: true
        web_name: Total track number
#      - name: trigger_str
#        type: string
#        web_name: Triggers (string)
#      - name: primary_vertex
#        type: bool
#        web_name: Primary vertex
