version: '3'
services:
    emd:
        build: .
        container_name: nica-ems
        restart: always
        ports:
          - 80:8080
        volumes:
          - ./src/jvmMain/resources/event-config-example.yaml:/root/event-config.yaml