services:
  emd:
    build:
      context: .
      dockerfile: Dockerfile.with-build
    container_name: nica-emd
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./ems.bmn-config.yaml:/app/bin/ems.config.yaml