version: '3'
services:
    emd:
        build: .
        container_name: nica-ems
        restart: always
        ports:
          - 80:8080
        volumes:
          - ./ems.config.example.yaml:/app/bin/ems.config.yaml