event_db:
  host: 192.168.65.52
  port: 5000
  db_name: event_db
  user: postgres
  password: example  # Note: needed anyway - for getting stats

condition_db:
  host: 192.168.65.52
  port: 5001
  db_name: bmn_db
  user: user
  password: user_pass

database_auth: True

#keycloak_auth:
#  server_url: "https://bmn-user.jinr.ru"
#  realm: "BMN"
#  client_id: "emd_api"
#  client_secret: "*****"

title: BM@N Event Metadata System

# Note: we now support only one page per EMS instance
pages:
  - name: BM@N Events
    api_url: /event_api/v1
    db_table_name: event
    default_limit_web: 100
    parameters:
      - name: track_number
        type: int
        intervals: true
        web_name: Total track number
#      - name: trigger_str
#        type: string
#        web_name: Triggers (string)
#      - name: primary_vertex
#        type: bool
#        web_name: Primary vertex
