services:

  event_db:
    image: postgres:13.2
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: example
    volumes:
      # Database files dir:  
      - ./event_db/data:/var/lib/postgresql/data
      # Initialization scripts (only run if database files dir is empty):
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ems_web_api:
    image: nica-ems:buildindocker
    restart: always
    ports: 
      - 80:8080
    volumes:
      - ./ems-test-config.yaml:/root/event-config.yaml

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

