services:

  event_db:
    image: postgres:13.2
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: example
    volumes:
      # Database files dir:  
      - ./event_db/data:/var/lib/postgresql/data
      # Initialization scripts (only run if database files dir is empty):
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ems_web_api:
    image: nica-emd:0.1.2
    restart: always
    ports: 
      - 80:8080
    volumes:
      - ./ems-test-config.yaml:/root/event-config.yaml

#  db_condition:
#    image: postgres
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: user_pass
#      POSTGRES_DB: bmn_db
#   ports:
#      - 5001:5432
#    volumes:
#      - ./condition_db/db/init/postgres:/docker-entrypoint-initdb.d
#      - ./condition_db/db/data/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

