db_connection:
  host: 192.168.65.52
  port: 5000
  db_name: event_db
  user: postgres
  password: example

title: "Event Index Main Page"

pages:
  - name: "BM@N Events"
    api_url: "/event_api/v1/bmn"
    web_url: "/event_web/bmn"  # Web search form URL
    db_table_name: "bmn_event"
    parameters:
      - name: track_number
        type: int
        intervals: true
        web_name: "Total track number"

  - name: "BM@N SRC Events"
    api_url: "/event_api/v1/src"
    web_url: "/event_web/src"  # Web search form URL
    db_table_name: "src_event"
    parameters:
      - name: track_number
        type: int
        intervals: true
        web_name: "Total track number"
      - name: input_charge
        type: float
        intervals: true
        web_name: "Input charge"
      - name: output_charge
        type: float
        intervals: true
        web_name: "Output charge"
