version: '3.1'

services:

  db:
    image: postgres:13.2
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./event_db/db/data/postgres/data:/var/lib/postgresql/data

  db_condition:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: bmn_db
    ports:
      - 5001:5432
    volumes:
      - ./condition_db/db/init/postgres:/docker-entrypoint-initdb.d
      - ./condition_db/db/data/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
